{
    'name': 'LinkedERP Helpdesk Modifier',
    'version': '1.0.5',
    'summary': 'Auto email reminder for unanswered helpdesk tickets after 3 days',
    'category': 'Helpdesk',
    'author': 'LinkedERP',
    'website': 'https://linkederp.com',
    'license': 'LGPL-3',
    'depends': [
        'helpdesk',
        'helpdesk_sale',
        'mail',
        'hr_timesheet',
        'helpdesk_sale_timesheet',
    ],
    'data': [
        'data/mail_template_data.xml',
        'data/ir_cron_data.xml',
        'views/helpdesk_team_views.xml',
        'views/helpdesk_ticket_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
